innerDiameter = 14 --mm
outerDiameter = 32 --mm
yokeBaseWidth = 9 --mm
yokeBaseHeight = 17 --mm
yokeUpperWidth = 30 --mm
youkeUpperOuterHeight = 4 --mm
nYokes = 6
FWWidth = 7 --mm
FWHeight = 14 --mm
padding = 0.2 --mm
rotorTurns = 150 --turns
rotorCurrent = 5 --A
innerStatorRadius = 44 --mm
airGap = 1 --mm
